version: "3.8"

services:
  nuxt-app:
    container_name: "nuxt-app"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - 50082:8080
    volumes:
      - ./nuxt-app/:/app
    working_dir: /app
    environment:
      TZ: "Asia/Tokyo" 
