name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./nuxt-app/package-lock.json
      - name: Package install
        run: cd ./nuxt-app && npm ci
      - name: Create .env file
        run: |
          cd ./nuxt-app && touch .env
          echo API_URL=${{ secrets.API_URL }} > .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
      - name: Build App
        run: cd ./nuxt-app && npm run generate --if-present
      # - name: Run Test
      #   run: cd /nuxt-app && npm test --if-present
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nuxt-app/dist
