name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compose up docker
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker compose up -d
    - name: Build Nuxt app
      run: docker exec -dt nuxt-app cd nuxt-app && npm run generate
